name: medal-reactivateor
on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 */3 * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
        - name: Run action
          uses: vc-teahouse/medal-reactivateor@main
          with:
            cookies: ${{secrets.BILI_MAIN_TOKEN}}
