name: medal-reactivateor
on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 */3 * *"
jobs:
  helper:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v4.2.2
          with:
            repository: vc-teahouse/medal-reactivateor
        - name: Run action
          uses: ./
          with:
            cookies: ${{secrets.BILI_MAIN_TOKEN}}
        - name: Run action
          uses: ./
          with:
            cookies: ${{secrets.BILI_TOKEN}}
